"""Create a standalone Arduino sketch folder; do not mix the root .ino files."""
from pathlib import Path
root = Path(__file__).resolve().parents[1]
source = (root/'ArduinoProj/combined_state_sequence.ino').read_text()
header = (root/'ArduinoProj/encoder_motion/EncoderMotion.h').read_text()
source = source.replace('#include "encoder_motion/EncoderMotion.h"', header)
folder = root/'ArduinoProj/combined_encoder_v3'
folder.mkdir(exist_ok=True)
(folder/'combined_encoder_v3.ino').write_text(
    '// Generated by tests/prepare-combined-sketch.py; edit combined_state_sequence.ino then regenerate.\n' + source)
print(folder/'combined_encoder_v3.ino')
